name: NodeJS with Webpack

on:
  push:
    branches: [ "ppc" ]
  pull_request:
    branches: [ "ppc" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 25.x]

    steps:
    - uses: actions/checkout@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx tsc
        npx webpack

    - name: Upload compiled JS
      uses: actions/upload-artifact@v6
      with:
        name: compiled-js
        path: dist/dom2svg.js